CREATE USER IF NOT EXISTS SA SALT 'a34fe51ba590d505' HASH '219c2f189a0425ef4417d87e22a2722191d6721018b52086a5bddd2bf32cec39' ADMIN;
CREATE CACHED TABLE PUBLIC.NEWS(
    NEWSID INT NOT NULL,
    TITLE VARCHAR,
    DESCRIPTION VARCHAR,
    TYPE VARCHAR
);
ALTER TABLE PUBLIC.NEWS ADD CONSTRAINT PUBLIC.CONSTRAINT_2 PRIMARY KEY(NEWSID);
-- 5 +/- SELECT COUNT(*) FROM PUBLIC.NEWS;
INSERT INTO PUBLIC.NEWS(NEWSID, TITLE, DESCRIPTION, TYPE) VALUES
(1, 'NEWS1', 'NEWS from table row1', 'GOOD'),
(2, 'NEWS2', 'NEWS from table row2', 'BAD'),
(3, 'NEWS3', 'NEWS from table row3', 'GOOD'),
(4, 'NEWS4', 'NEWS frm table row 4', 'GOOD'),
(5, 'NEWS5', 'NEWS frm table row 5', 'GOOD');
CREATE CACHED TABLE PUBLIC.USERDETAILS(
	ID INTEGER NOT NULL,
    USERNAME VARCHAR NOT NULL,
    FIRSTNAME VARCHAR NOT NULL,
    LASTNAME VARCHAR NOT NULL,
    PASSWORD VARCHAR NOT NULL
);
ALTER TABLE PUBLIC.USERDETAILS ADD CONSTRAINT PUBLIC.CONSTRAINT_6 PRIMARY KEY(ID);
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.USERDETAILS;
INSERT INTO PUBLIC.USERDETAILS(ID, USERNAME, FIRSTNAME, LASTNAME, PASSWORD) VALUES
(1,'test', 'shital', 'patil', 'test'),
(2,'user', 'user', 'user', 'user'),
(3,'dummy', 'dummy', 'dummy', 'dummy');
CREATE CACHED TABLE PUBLIC.STOCKS(
    STOCKID VARCHAR NOT NULL,
    STOCKDESCR VARCHAR,
    MKTVAL FLOAT,
    STOCKQTY INTEGER
);
ALTER TABLE PUBLIC.STOCKS ADD CONSTRAINT PUBLIC.CONSTRAINT_9 PRIMARY KEY(STOCKID);
-- 9 +/- SELECT COUNT(*) FROM PUBLIC.STOCKS;
INSERT INTO PUBLIC.STOCKS(STOCKID, STOCKDESCR, MKTVAL, STOCKQTY) VALUES
('compA', 'company A', 40.0, 50),
('compB', 'company B', 45.0, 50),
('compC', 'company C', 45.0, 50),
('compD', 'company D', 45.0, 50),
('compE', 'company E', 45.0, 50),
('compF', 'company F', 45.0, 50),
('compG', 'company G', 45.0, 50),
('compH', 'company H', 45.0, 50),
('compI', 'company I', 45.0, 50);
CREATE CACHED TABLE PUBLIC.USERTRADEACCT(
    USERNAME VARCHAR NOT NULL,
    BALANCE FLOAT
);
ALTER TABLE PUBLIC.USERTRADEACCT ADD CONSTRAINT PUBLIC.CONSTRAINT_E PRIMARY KEY(USERNAME);
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.USERTRADEACCT;
INSERT INTO PUBLIC.USERTRADEACCT(USERNAME, BALANCE) VALUES
('user', 940.0),
('test', 1060.0);
CREATE CACHED TABLE PUBLIC.USERHOLDING(
    USERNAME VARCHAR NOT NULL,
    STOCKID VARCHAR NOT NULL,
    STOCKQTY INT,
    PRICE FLOAT
);
ALTER TABLE PUBLIC.USERHOLDING ADD CONSTRAINT PUBLIC.CONSTRAINT_4 PRIMARY KEY(USERNAME, STOCKID);
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.USERHOLDING;
INSERT INTO PUBLIC.USERHOLDING(USERNAME, STOCKID, STOCKQTY, PRICE) VALUES
('test', 'compA', 1, 40.0),
('user', 'compA', 3, 160.0);
CREATE CACHED TABLE PUBLIC.TRADETXN(
    USERNAME VARCHAR NOT NULL,
    TXNTYPE VARCHAR NOT NULL,
    STOCKID VARCHAR NOT NULL,
    STOCKQTY INTEGER,
    STATUS VARCHAR,
    CREATEDAT DATETIME DEFAULT NOW() NOT NULL,
    PRICE FLOAT
);
ALTER TABLE PUBLIC.TRADETXN ADD CONSTRAINT PUBLIC.CONSTRAINT_7 PRIMARY KEY(USERNAME, TXNTYPE, STOCKID, CREATEDAT);
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.TRADETXN;
INSERT INTO PUBLIC.TRADETXN(USERNAME, TXNTYPE, STOCKID, STOCKQTY, STATUS, CREATEDAT, PRICE) VALUES
('test', 'sale', 'compA', 1, 'S', TIMESTAMP '2015-10-29 14:05:45.609', 60.0),
('user', 'buy', 'compA', 1, 'S', TIMESTAMP '2015-10-29 14:06:04.393', 60.0);
